### ISSUE TITLE
Implement Column Group Tables

### ISSUE THREAD

**Issue by pastelmind** [pastelmind/d2txt#15]
## Introduction
Column Groups were proposed in #3 and implemented in #14. In doing so, I discovered that several types of columns are not suitable for describing with [TOML arrays](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md#array).

For example, several item-related TXT files have multiple fields with names like `modXcode`, `modXparam` `modXmin`, `modXmax`, where `X` is a positive integer. Such fields are clearly meant to be edited as one subgroup, so it is desirable to place each on a single line. Using TOML arrays, they can be grouped like this:

```toml
[[items]]
id = 1
--mod1 = ['damage', '100', '200']
--mod2 = ['fire-damage', '50', '60']
--mod3 = ['swing', '20', '20']
```

Note that the member columns have heterogeneous types--`modXcode` is a string, while other fields are numbers. Since arrays in TOML v0.5.0 spec disallow heterogeneous types, integer fields must be encoded as strings, or use the "nested array trick":

```toml
--mod1 = [['damage'], [100], [200]]
```

This is ugly.

Since each value in this group has a different meaning, placing them in a single array--a data structure meant to store multiple entries of the same type--is fundamentally awkward.

In addition, one has to memorize the order of each value within the group. I attempted to solve this by providing descriptive column group aliases:

```toml
--mod1-CodeMinMax = [['damage'], [100], [200]]
```

But this is just as ugly and hard to decipher.

## Inline Tables
This type of data is suited for nested dictionaries. In TOML, such data structures can be described compactly using [inline tables](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md#inline-table):

```toml
[[items]]
id = 1
mod1 = { code = 'damage', min = 100, max = 200 }
mod2 = { code = 'fire-damage', min = 50,  max = 60 }
mod3 = { code = 'swing', min = 20, max = 20 }
```

There are two other possible formats, both more verbose than inline tables. Dotted child [tables](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md#table):

```toml
[[items]]
id = 1

[items.mod1]
code = 'damage'
min = 100
max = 200

[items.mod2]
code = 'fire-damage'
min = 50
max = 60

[items.mod3]
code = 'swing'
min = 20
max = 20
```

...and dotted [keys](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md#keys):

```toml
[[items]]
id = 1
mod1.code = 'damage'
mod1.min = 100
mod1.max = 200
mod2.code = 'fire-damage'
mod2.min = 50
mod2.max = 60
mod3.code = 'swing'
mod3.min = 20
mod3max = 20
```

These forms, are more verbose than tables without column groups. Inline tables are clearly better for the job.

### Column Group Tables

Keys for column group tables are prefixed with two underscores (`__`). This keeps them visually distinct from column group arrays, which are prefixed with two dashes (`--`).

Example:

```toml
__rArm = { left = 5, right = 10, top = 20, bottom = 25 }
```

Since each subkey describes the purpose of each value, the key (alias) should be short. Less than 12 characters is good.

Column group tables should ideally have between 2 and 6 values. Each value should have a distinct meaning (cf. `etype1`, `etype2`, `etype3`, ...).

### Column Group Metadata

The `column_groups` table at the top of each TOML file describes the column groups used in the file. Each key-value pair describes a column group array: the key is the column group alias, and the value is an array of member columns.

This format can be extended to describe column group tables as well:

```toml
[[column_groups]]
 # Metadata for column group arrays
--Mod1-MinMax = ['mod1code', 'mod1min', 'mod1max']
--Mod2-MinMax = ['mod2code', 'mod2min', 'mod2max']
--Mod3-MinMax = ['mod3code', 'mod3min', 'mod3max']
 # Metadata for column group tables
--Mod1 = { code = 'mod1code', min = 'mod1min', max = 'mod1max' }
--Mod2 = { code = 'mod2code', min = 'mod2min', max = 'mod2max' }
--Mod3 = { code = 'mod3code', min = 'mod3min', max = 'mod3max' }
```

Subkeys such as  `code`, `min`, and `max` are henceforth referred to as *column member aliases*, or member aliases for short.

The metadata maps member aliases to member column names to keep consistent with how the inline tables are used in rows. It also allows us to parse TOML slightly faster, since this metadata can be converted to mappings of member aliases to column names.

## Implementation

Both [toml] and [qtoml] can parse inline tables. Unfortunately, neither supports generating inline tables via public APIs.

I skimmed the source code of toml v0.10.0 and qtoml 0.3.0. Both packages *do* support generating inline tables from dictionaries, though not easily.

[toml]: https://github.com/uiri/toml
[qtoml]: https://github.com/alethiophile/qtoml

### Hacking toml
toml [generates an inline table](https://github.com/uiri/toml/blob/0.10.0/toml/encoder.py#L210) if a [`toml.TomlEncoder`] initialized with `preserve=True` is used *and* the object is an instance of [`toml.decoder.InlineTableDict`]. This class is a direct subclass of [`object`] and therefore cannot be used as a mapping. However, [`toml.TomlDecoder`] provides the [`get_empty_inline_table()`] method, which returns a an `InlineTableDict` instance that also subclasses [`dict`]. Easy peasy. Too bad we don't use `toml.dumps()`--[it's bugged](https://github.com/pastelmind/d2txt/issues/9#issuecomment-575980107).

### Hacking qtoml
qtoml [generates an inline table](https://github.com/alethiophile/qtoml/blob/v0.3.0/qtoml/encoder.py#L177) for an object if [`qtoml.encoder.TOMLEncoder.is_scalar()`] returns `True`. Normally, this only occurs if [a dictionary is inside a list inside another list](https://github.com/alethiophile/qtoml/blob/v0.3.0/qtoml/encoder.py#L68). I tried to circumvent this by creating a custom `dict` subclass, which I added to [`qtoml.TOMLEncoder.st`] as the *key* with [`TOMLEncoder.dump_itable`] as the value.

```python
from qtoml.encoder import TOMLEncoder

class MyInlineDict(dict):
    pass

hacked_encoder = TOMLEncoder()
hacked_encoder.st[MyInlineDict] = hacked_encoder.dump_itable
```

 This made the encoder generate inline tables for instances of my custom class. Unfortunately, it was _also_ generating nested tables for the same data:

```toml
[[items]]
mod1 = { code = 'damage', min = 100, max = 200 }
mod2 = { code = 'damage', min = 150, max = 250 }

[items.mod1]
code = 'damage'
min = 100
max = 200

[items.mod2]
code = 'damage'
min = 150
max = 250
```

This is because the current implementation of [`TOMLEncoder.dump_sections()`] always renders `dict` instances as individual sections. Thus, we need a custom mapping class that is *not* a subclass of `dict`.

Fortunately, the standard library already provides such a class: [`collections.UserDict`]. It acts just like a `dict`, except that `isinstance(o, dict)` returns `False`.

Final solution:

```python
from qtoml.encoder import TOMLEncoder
from collections import UserDict

hacked_encoder = TOMLEncoder()
hacked_encoder.st[UserDict] = hacked_encoder.dump_itable

# Use hacked_encoder.dump_sections(o, [], True) to dump TOML
```

[`collections.UserDict`]: https://docs.python.org/3/library/collections.html#collections.UserDict
[`qtoml.encoder.TOMLEncoder.is_scalar()`]: https://github.com/alethiophile/qtoml/blob/v0.3.0/qtoml/encoder.py#L198
[`qtoml.TOMLEncoder.st`]: https://github.com/alethiophile/qtoml/blob/v0.3.0/qtoml/encoder.py#L47
[`TOMLEncoder.dump_itable`]: https://github.com/alethiophile/qtoml/blob/v0.3.0/qtoml/encoder.py#L156
[`TOMLEncoder.dump_sections()`]: https://github.com/alethiophile/qtoml/blob/v0.3.0/qtoml/encoder.py#L186
